{% extends "base.rq" %}
{% block query %}
SELECT ?proxy ?label ?pfp_uri
WHERE {
{SELECT ?proxy ?label where {
	?proxy a crm:E21_Person ;
     	rdfs:label ?label .
	FILTER(CONTAINS(?label, "{{ label }}"))
}
}
?proxy pfps:proxy_for ?pfp_uri .
}
{% endblock query %}
